Visual Studio 2017 project file updated with the PNG and JXL stuff, but it won't build presumably because the lib files were built with 2019.
LINK : fatal error C1900: Il mismatch between 'P1' version '20210202' and 'P2' version '20180423'

TODO for another time, to make a 2017 release (to attempt XP compatibility), see #51